const { Scheme } = require("./Scheme.js");
const { Task } = require("./Task");
const { generateTasks } = require("../Services/SchedulingService.js");
const { where, and, documentId } = require("firebase/firestore/lite");

class PlantSaved extends Scheme {
  constructor() {
    super([
      "userId",
      "plantApiId",
      "commonName",
      "scientificName",
      "imageURL",
      "plantType",
      "dateAdded",
    ]);
    this.tablename = "PlantSaved";
    // Add Task instance - used to save generated tasks
    this.task = new Task();
  }

//   async AddNewDocument(props) {
//     let res = await super.AddNewDocument(props, this.tablename);
//     return res;
//   }

//   async AddNewDocument(props) {

//     let res = await super.AddNewDocument(props, this.tablename);

//     if (res.status !== 200) {
//         return res;
//     }
//     console.log("Plant saved successfully");

//     const generatedTask = generateTasks(props, props.dateAdded);
//     console.log("Generated tasks:");
//     console.log(generateTasks);

//     return res;
//   }

  async AddNewDocument(props) {

    // Save plant to Firestore
    let res = await super.AddNewDocument(props, this.tablename);

    // Test save response
    console.log("\nSAVE RESPONSE\n");
    console.log(res);

    // Stop if plant save fails
    if (res.status !== 200) {
        return res;
    }

    // console.log("\nPLANT SAVED\n");
    // console.log(props);

    // Generate plant care tasks
    const generatedTasks = generateTasks(props, props.dateAdded);

    // ==================================
    // TEMP DEBUGGING CODE
    // Used to test that generated tasks can be saved to Firestore 
    // ==================================

    // console.log("\nTESTING FIRST TASK SAVE\n");

    // First generated Task from array
    const firstTask = generatedTasks[0];

    // console.log("\nFIRST TASK\n");
    // console.log(firstTask);

    // Build complete task object to match Task.js
    const testTask = {
      // Link Task to curent User
      userId: props.userId,
      // Temp test value (to be replaced with Saved Plant ID)
      savedPlantID: "TEST123",

      //Fields generated by SchedulingService
      commonName: firstTask.commonName,
      taskName: firstTask.taskName,
      frequencyDays: firstTask.frequencyDays,
      dueDate: firstTask.dueDate,
      completed: firstTask.completed,
      // completed: true,
      // completedDate: firstTask.completedDate,
      // completedDate: "",
      completedDate: "TESTING_NULL_FIELD",  // temp test validation
      createdDate: firstTask.createdDate
    }

    try {
      // console.log("\nTEST TASK OBJECT\n");
      // console.log(testTask);

      // Test Save task to Firestore
      const taskResult = await this.task.AddNewDocument(testTask);
      // Show result returned from Task.js
      console.log("\nTASK SAVE RESULT\n");
      console.log(taskResult);
      console.log("\nTASK DOCUMENT ID\n");
      console.log(taskResult.data.id);
    }
    catch(error) {
      console.log("\nTASK SAVE ERROR\n");
      console.log(error);
    }

    // console.log("\nGENERATED TASKS\n");
    // console.log(generatedTasks);

    return res;
  }


  async GetCurrentUserSavedPlantList() {
    try {
      let res = await this.firebase.GetCollectionThatContainCurrentUser(
        this.tablename,
      );
      return res;
    } catch (error) {
      return {
        status: 500,
        error: error,
      };
    }
  }
  async GetCurrentUserSingleSavePlant(ID) {
    try {
      let res =
        await this.firebase.GetCollectionThatContainCurrentUserWithCustomQuery(
          this.tablename,
          where(documentId(), "==", ID),
        );
      return res;
    } catch (error) {
      return {
        status: 500,
        error: error,
      };
    }
  }
  async RemoveItemPlantList(plantID) {
    try {
      let res = await this.firebase.RemoveDocumentFromCollection(
        this.tablename,
        plantID,
      );
      return res;
    } catch (error) {
      return {
        status: 500,
        message: error,
      };
    }
  }
}

module.exports = { PlantSaved };

/*4. Save tasks
Tasks are stored in Firebase.

Example:

{
"userId": 3,
"plantID": 2320,
"plantName": "carrot",
"taskType": "Check soil and water if dry",
"frequencyDays": 1,
"dueDate": "2026-06-02",
"completed": false
}

{
"plantId": 2320,
"userId": "3",
"plantName": "Carrot",
"plantType": "Vegetable",
"plantCareLevel": "High",
"sunlight": "Full sun",
"watering": "Frequent",
"imageURL": "URL",
"dateAdded": "2026-06-01"
}


*/
