const { Scheme } = require("./Scheme.js");
const { Task } = require("./Task");
const { generateTasks } = require("../Services/SchedulingService.js");
const { where, and, documentId } = require("firebase/firestore/lite");

class PlantSaved extends Scheme {
  constructor() {
    super([
      "userId",
      "plantApiId",
      "commonName",
      "scientificName",
      "imageURL",
      "plantType",
      "dateAdded",
    ]);
    this.tablename = "PlantSaved";
    // Add Task instance - used to save generated tasks
    this.task = new Task();
  }


  async AddNewDocument(props) {

    // Save plant to Firestore
    let res = await super.AddNewDocument(props, this.tablename);

    // Stop if plant save fails
    if (res.status !== 200) {
        return res;
    }

    // Generate plant care tasks
    const generatedTasks = generateTasks(props, props.dateAdded);

    // PlantSaved Firestore collection doc ID
    const savedPlantID = res.data.id;

    // Save generated tasks
    for (const task of generatedTasks) {
      const saveTask = {
      // Link Task to curent User
      userId: props.userId,
      savedPlantID: savedPlantID,
      //Fields generated by SchedulingService
      commonName: task.commonName,
      taskName: task.taskName,
      frequencyDays: task.frequencyDays,
      dueDate: task.dueDate,
      completed: false,
      completedDate: "NOT_COMPLETED",
      createdDate: task.createdDate
    }
    await this.task.AddNewDocument(saveTask);
    // // Test
    // console.log(saveTask);
  }

  return res;

  }


  async GetCurrentUserSavedPlantList() {
    try {
      let res = await this.firebase.GetCollectionThatContainCurrentUser(
        this.tablename,
      );
      return res;
    } catch (error) {
      return {
        status: 500,
        error: error,
      };
    }
  }
  async GetCurrentUserSingleSavePlant(ID) {
    try {
      let res =
        await this.firebase.GetCollectionThatContainCurrentUserWithCustomQuery(
          this.tablename,
          where(documentId(), "==", ID),
        );
      return res;
    } catch (error) {
      return {
        status: 500,
        error: error,
      };
    }
  }
  async RemoveItemPlantList(plantID) {
    try {
      let res = await this.firebase.RemoveDocumentFromCollection(
        this.tablename,
        plantID,
      );
      return res;
    } catch (error) {
      return {
        status: 500,
        message: error,
      };
    }
  }
}

module.exports = { PlantSaved };

/*4. Save tasks
Tasks are stored in Firebase.

Example:

{
"userId": 3,
"plantID": 2320,
"plantName": "carrot",
"taskType": "Check soil and water if dry",
"frequencyDays": 1,
"dueDate": "2026-06-02",
"completed": false
}

{
"plantId": 2320,
"userId": "3",
"plantName": "Carrot",
"plantType": "Vegetable",
"plantCareLevel": "High",
"sunlight": "Full sun",
"watering": "Frequent",
"imageURL": "URL",
"dateAdded": "2026-06-01"
}


*/
